name: Release FakePs4

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          # --- LINUX CONFIGURATION ---
          - os: ubuntu-latest
            make: make
            binary_name: FakePs4
            output_name: FakePs4-linux
            shell: bash
            qt_arch: gcc_64
            
          # --- WINDOWS CONFIGURATION ---
          - os: windows-latest
            make: nmake
            binary_name: FakePs4.exe
            output_name: FakePs4-windows.exe
            shell: cmd
            qt_arch: win64_msvc2019_64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC Compiler (Windows only)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        target: 'desktop'
        # Explicitly tell Qt which architecture to use
        arch: ${{ matrix.qt_arch }}

    # Notice the 'shell' parameter here!
    - name: Generate Makefile
      shell: ${{ matrix.shell }}
      run: qmake FakePs4.pro

    - name: Compile Project
      shell: ${{ matrix.shell }}
      run: ${{ matrix.make }}

    - name: Prepare Binary Names
      shell: bash
      run: |
        cd bin
        mv ${{ matrix.binary_name }} ${{ matrix.output_name }}

    - name: Upload Binaries to Release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/${{ matrix.output_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}